# Generated by Django 4.1.3 on 2023-07-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.song'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.playlist'),
        ),
    ]
