# Generated by Django 4.1.3 on 2023-07-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_liked_songs_customuser_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='api.song'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='playlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='api.playlist'),
        ),
    ]
