# Generated by Django 4.1.3 on 2023-07-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_liked_songs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.song'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
